#!/usr/bin/env python3
"""Upload keyboard/Resources' large files to the Hugging Face model repo.

    hf auth login
    research/.venv/bin/python keyboard/tools/upload_models.py [--repo edwarddgao/glyph-models] [--create]

Uploads exactly what fetch_models.py fetches, plus a model card. Run after an
export changed a model or table.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from fetch_models import HF_REPO, PATTERNS, RESOURCES

CARD = """---
license: mit
tags: [swipe-typing, gesture-typing, keyboard, coreml, ios]
---
# Glyph decoder resources

Core ML models and tables for [Glyph](https://github.com/edwarddgao/glyph), an
open-source iPhone swipe keyboard. `SwipeAREncoder` / `SwipeARStep`: the
autoregressive swipe decoder (research run `ar_mixed_s1`, TCN trunk + 2-layer
transformer letter decoder, 1.7M parameters, fp32). `SwipeLM`: distilgpt2 fp16
gather model for the fused sentence search. `lexicon.bin`: 301,508-word trie
(FUTO training words blended with wordfreq English) with unigram
log-probabilities. `ilm.bin`, `priors.bin`: the encoder's internal-LM and the
LM's marginal prior per trie node. `gpt2/`: tokenizer files.
`bench_gestures.json`: the replay-benchmark gestures. `*goldens.json`: test
vectors the Swift port is checked against. Regenerated by the `tools/export_*.py`
scripts in the repo; how each was chosen is in `research/README.md`.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=HF_REPO)
    ap.add_argument("--create", action="store_true", help="create the repo if it does not exist")
    a = ap.parse_args()
    from huggingface_hub import HfApi
    api = HfApi()
    if a.create:
        api.create_repo(a.repo, repo_type="model", exist_ok=True)
    (RESOURCES / "README.md").write_text(CARD)
    api.upload_folder(folder_path=str(RESOURCES), repo_id=a.repo, repo_type="model",
                      allow_patterns=PATTERNS + ["README.md"], commit_message="update decoder resources")
    (RESOURCES / "README.md").unlink()
    print(f"uploaded to https://huggingface.co/{a.repo}")


if __name__ == "__main__":
    main()
